# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=25)),
                ('product_price', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('product_description', models.CharField(default='', max_length=1000)),
                ('product_color', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(default='', max_length=25)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Categories')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.SubCategories'),
        ),
    ]
